import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import LogIn from "./components/LogIn";
import { UserProvider } from "@/utils/contexts";
import LogInWrapper from "./components/LogInWrap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Header />
          <UserProvider>
          <LogInWrapper children={children} />
        </UserProvider >
      </body>
    </html>
  );
}
